-- Admin roles and audit log for secure administrative management
-- Safe/idempotent migration for Supabase (Postgres)

begin;

create table if not exists public.admin_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('ADMIN', 'SUPER_ADMIN')),
  active boolean not null default true,
  granted_by uuid references auth.users(id),
  granted_at timestamptz not null default now(),
  revoked_by uuid references auth.users(id),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_admin_roles_active_user_unique
  on public.admin_roles(user_id)
  where active = true;

create index if not exists idx_admin_roles_active_role
  on public.admin_roles(role)
  where active = true;

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  old_role text,
  new_role text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_audit_target on public.admin_audit_log(target_user_id);
create index if not exists idx_admin_audit_actor on public.admin_audit_log(actor_user_id);
create index if not exists idx_admin_audit_created_at on public.admin_audit_log(created_at desc);

alter table public.admin_roles enable row level security;
alter table public.admin_audit_log enable row level security;

create or replace function public.is_super_admin(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  return exists (
    select 1
    from public.admin_roles ar
    where ar.user_id = p_user_id
      and ar.active = true
      and ar.role = 'SUPER_ADMIN'
  );
end;
$$;

create or replace function public.is_admin_user(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  return exists (
    select 1
    from public.admin_roles ar
    where ar.user_id = p_user_id
      and ar.active = true
      and ar.role in ('ADMIN', 'SUPER_ADMIN')
  );
end;
$$;

create or replace function public.get_my_admin_role()
returns text
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_role text;
begin
  if auth.uid() is null then
    return null;
  end if;

  select ar.role
    into v_role
  from public.admin_roles ar
  where ar.user_id = auth.uid()
    and ar.active = true
  limit 1;

  return v_role;
end;
$$;

create or replace function public.list_active_admin_roles()
returns table (
  user_id uuid,
  email text,
  full_name text,
  role text,
  granted_at timestamptz,
  granted_by uuid,
  granted_by_email text,
  status text
)
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  if auth.uid() is null or not public.is_super_admin(auth.uid()) then
    raise exception 'forbidden';
  end if;

  return query
  select
    ar.user_id,
    lower(u.email::text) as email,
    coalesce(u.raw_user_meta_data->>'name', u.raw_user_meta_data->>'full_name') as full_name,
    ar.role,
    ar.granted_at,
    ar.granted_by,
    lower(g.email::text) as granted_by_email,
    case when ar.active then 'ACTIVE' else 'INACTIVE' end as status
  from public.admin_roles ar
  join auth.users u on u.id = ar.user_id
  left join auth.users g on g.id = ar.granted_by
  where ar.active = true
  order by ar.role desc, ar.granted_at asc;
end;
$$;

create or replace function public.grant_admin_role_by_email(p_target_email text, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_target_id uuid;
  v_old_role text;
  v_super_count integer;
begin
  v_actor := auth.uid();

  if v_actor is null or not public.is_super_admin(v_actor) then
    raise exception 'forbidden';
  end if;

  if p_role not in ('ADMIN', 'SUPER_ADMIN') then
    raise exception 'invalid role';
  end if;

  select u.id into v_target_id
  from auth.users u
  where lower(u.email::text) = lower(trim(p_target_email))
  limit 1;

  if v_target_id is null then
    raise exception 'target user not found';
  end if;

  select ar.role into v_old_role
  from public.admin_roles ar
  where ar.user_id = v_target_id and ar.active = true
  limit 1;

  if v_old_role = p_role then
    return;
  end if;

  if v_old_role = 'SUPER_ADMIN' and p_role = 'ADMIN' then
    select count(*) into v_super_count
    from public.admin_roles ar
    where ar.active = true and ar.role = 'SUPER_ADMIN';

    if v_super_count <= 1 then
      raise exception 'cannot downgrade the last super admin';
    end if;
  end if;

  update public.admin_roles
  set active = false,
      revoked_at = now(),
      revoked_by = v_actor
  where user_id = v_target_id
    and active = true;

  insert into public.admin_roles (user_id, role, active, granted_by, granted_at)
  values (v_target_id, p_role, true, v_actor, now());

  insert into public.admin_audit_log (target_user_id, actor_user_id, action, old_role, new_role)
  values (v_target_id, v_actor, 'GRANT_OR_CHANGE_ROLE', v_old_role, p_role);
end;
$$;

create or replace function public.change_admin_role(p_target_user_id uuid, p_new_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.grant_admin_role_by_email((select u.email::text from auth.users u where u.id = p_target_user_id), p_new_role);
end;
$$;

create or replace function public.revoke_admin_role(p_target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_old_role text;
  v_super_count integer;
begin
  v_actor := auth.uid();

  if v_actor is null or not public.is_super_admin(v_actor) then
    raise exception 'forbidden';
  end if;

  select ar.role into v_old_role
  from public.admin_roles ar
  where ar.user_id = p_target_user_id and ar.active = true
  limit 1;

  if v_old_role is null then
    return;
  end if;

  if v_old_role = 'SUPER_ADMIN' then
    select count(*) into v_super_count
    from public.admin_roles ar
    where ar.active = true and ar.role = 'SUPER_ADMIN';

    if v_super_count <= 1 then
      raise exception 'cannot revoke the last super admin';
    end if;
  end if;

  update public.admin_roles
  set active = false,
      revoked_at = now(),
      revoked_by = v_actor
  where user_id = p_target_user_id
    and active = true;

  insert into public.admin_audit_log (target_user_id, actor_user_id, action, old_role, new_role)
  values (p_target_user_id, v_actor, 'REVOKE_ROLE', v_old_role, null);
end;
$$;

-- RLS policies

drop policy if exists "Users can read own active admin role" on public.admin_roles;
create policy "Users can read own active admin role"
  on public.admin_roles
  for select
  to authenticated
  using (auth.uid() = user_id and active = true);

drop policy if exists "Super admins can read all admin roles" on public.admin_roles;
create policy "Super admins can read all admin roles"
  on public.admin_roles
  for select
  to authenticated
  using (public.is_super_admin(auth.uid()));

drop policy if exists "Super admins can read admin audit" on public.admin_audit_log;
create policy "Super admins can read admin audit"
  on public.admin_audit_log
  for select
  to authenticated
  using (public.is_super_admin(auth.uid()));

-- Keep writes function-only
revoke insert, update, delete on public.admin_roles from anon, authenticated;
revoke insert, update, delete on public.admin_audit_log from anon, authenticated;

-- RPC execution grants
revoke execute on function public.is_super_admin(uuid) from public, anon;
revoke execute on function public.is_admin_user(uuid) from public, anon;
revoke execute on function public.get_my_admin_role() from public, anon;
revoke execute on function public.list_active_admin_roles() from public, anon;
revoke execute on function public.grant_admin_role_by_email(text, text) from public, anon;
revoke execute on function public.change_admin_role(uuid, text) from public, anon;
revoke execute on function public.revoke_admin_role(uuid) from public, anon;

grant execute on function public.is_super_admin(uuid) to authenticated;
grant execute on function public.is_admin_user(uuid) to authenticated;
grant execute on function public.get_my_admin_role() to authenticated;
grant execute on function public.list_active_admin_roles() to authenticated;
grant execute on function public.grant_admin_role_by_email(text, text) to authenticated;
grant execute on function public.change_admin_role(uuid, text) to authenticated;
grant execute on function public.revoke_admin_role(uuid) to authenticated;

-- Bootstrap: keep compatibility with existing hardcoded owner email when user exists
insert into public.admin_roles (user_id, role, active, granted_by, granted_at)
select u.id, 'SUPER_ADMIN', true, u.id, now()
from auth.users u
where lower(u.email::text) in ('dilioalvarenga@gmail.com')
  and not exists (
    select 1 from public.admin_roles ar where ar.user_id = u.id and ar.active = true
  );

commit;
